services:
    _instanceof:
        Psr\Log\LoggerAwareInterface:
            calls:
                - [setLogger, ['@logger']]
            tags:
                - { name: monolog.logger, channel: oro_marketing }

        Oro\Component\MessageQueue\Client\TopicSubscriberInterface:
            tags:
                - { name: oro_message_queue.client.message_processor }

    oro_marketing_list.async.update_marketing_list:
        class: Oro\Bundle\MarketingListBundle\Async\UpdateMarketingListProcessor
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@event_dispatcher'
