services:
    oro_marketing_list.entity_provider:
        alias: oro_entity.entity_provider
        public: true

    oro_marketing_list.datagrid.marketing_list_type.provider:
        class: Oro\Bundle\MarketingListBundle\Datagrid\GridMarketingListTypeProvider
        public: true
        arguments:
            - '@doctrine'

    oro_marketing_list.marketing_list.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\MarketingListBundle\Entity\MarketingList'
            - '@doctrine.orm.entity_manager'

    oro_marketing_list.marketing_list_removed_item.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
            - "@doctrine.orm.entity_manager"

    oro_marketing_list.marketing_list_unsubscribed_item.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
            - "@doctrine.orm.entity_manager"

    oro_marketing_list.contact_information_field_helper:
        class: Oro\Bundle\MarketingListBundle\Model\ContactInformationFieldHelper
        public: true
        arguments:
            - "@oro_entity_config.provider.entity"
            - "@oro_entity.doctrine_helper"
            - "@oro_query_designer.entity_field_provider"

    oro_marketing_list.contact_information_column_validator:
        class: Oro\Bundle\MarketingListBundle\Validator\Constraints\ContactInformationColumnValidator
        arguments:
            - "@oro_marketing_list.contact_information_field_helper"
        tags:
            - { name: validator.constraint_validator }

    oro_marketing_list.provider.contact_information_exclusion:
        class: Oro\Bundle\MarketingListBundle\Provider\ContactInformationExclusionProvider
        arguments:
            - "@oro_entity.virtual_field_provider"
            - "@oro_entity_config.provider.entity"
            - "@doctrine"

    oro_marketing_list.provider.chain_exclusion:
        class: Oro\Bundle\EntityBundle\Provider\ChainExclusionProvider
        calls:
            - [addProvider,  ["@oro_query_designer.exclusion_provider"]]
            - [addProvider,  ["@oro_marketing_list.provider.contact_information_exclusion"]]

    oro_marketing_list.entity_provider.contact_information:
        parent: oro_query_designer.entity_provider
        lazy: true
        calls:
            - [setExclusionProvider,  ["@oro_marketing_list.provider.chain_exclusion"]]

    oro_marketing_list.datagrid.listener.items:
        class: Oro\Bundle\MarketingListBundle\Datagrid\MarketingListItemsListener
        arguments:
            - "@oro_marketing_list.model.helper"
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after, method: onBuildAfter }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before, method: onBuildBefore, priority: 10 }

    oro_marketing_list.datagrid.action_permission_provider:
        class: Oro\Bundle\MarketingListBundle\Datagrid\ActionPermissionProvider
        public: true

    oro_marketing_list.security.acl.voter.segment:
        class: Oro\Bundle\MarketingListBundle\Acl\Voter\MarketingListSegmentVoter
        arguments:
            - "@oro_entity.doctrine_helper"
        calls:
            - [setClassName, ['Oro\Bundle\SegmentBundle\Entity\Segment']]
        tags:
            - { name: security.voter, priority: 500 }

    oro_marketing_list.provider.marketing_list:
        class: Oro\Bundle\MarketingListBundle\Provider\MarketingListProvider
        arguments:
            - "@oro_datagrid.datagrid.manager"

    oro_marketing_list.model.marketing_list_item_connector:
        class: Oro\Bundle\MarketingListBundle\Model\MarketingListItemConnector
        arguments:
            - "@doctrine"
            - "@oro_entity.doctrine_helper"

    oro_marketing_list.model.helper:
        class: Oro\Bundle\MarketingListBundle\Model\MarketingListHelper
        arguments:
            - "@doctrine"

    oro_marketing_list.datagrid.extension:
        class: Oro\Bundle\MarketingListBundle\Datagrid\Extension\MarketingListExtension
        arguments:
            - "@oro_marketing_list.model.helper"
        tags:
            - { name: oro_datagrid.extension }

    oro_marketing_list.form.autocomplete.marketing_list.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Oro\Bundle\MarketingListBundle\Entity\MarketingList'
            - ['name']
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: marketing_lists, acl_resource: oro_marketing_list_view }

    oro_marketing_list.twig.extension.contact_information_fields:
        class: Oro\Bundle\MarketingListBundle\Twig\ContactInformationFieldsExtension
        public: false
        arguments:
            - "@oro_platform.twig.service_locator"
        tags:
            - { name: twig.extension }

    oro_marketing_list.provider.contact_information_fields:
        class: Oro\Bundle\MarketingListBundle\Provider\ContactInformationFieldsProvider
        arguments:
            - "@oro_marketing_list.contact_information_field_helper"

    oro_marketing_list.datagrid.configuration.provider:
        class: Oro\Bundle\MarketingListBundle\Datagrid\ConfigurationProvider
        arguments:
            - "@oro_datagrid.configuration.provider.chain"
            - "@oro_entity_config.provider.form"
            - "@oro_marketing_list.model.helper"
        tags:
            - { name: oro_datagrid.configuration.provider, priority: -10 }

    oro_marketing_list.marketing_list.cache_warmer:
        class: Oro\Component\Config\Cache\ConfigCacheWarmer
        public: false
        arguments:
            - '@oro_marketing_list.provider.marketing_list_allowed_classes'
        tags:
            - { name: kernel.cache_warmer }

    oro_marketing.event_listener.marketing_list_entity_listener:
        class: 'Oro\Bundle\MarketingListBundle\EventListener\MarketingListEntityListener'
        public: false
        arguments:
            - '@oro_marketing_list.virtual_relation_cache'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\MarketingListBundle\Entity\MarketingList', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\MarketingListBundle\Entity\MarketingList', event: postUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\MarketingListBundle\Entity\MarketingList', event: postRemove }

    oro_marketing_list.virtual_relation_cache:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_marketing_list' }

    oro_marketing_list.virtual_relation_provider.marketing_list:
        class: Oro\Bundle\MarketingListBundle\Provider\MarketingListVirtualRelationProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - '@oro_marketing_list.virtual_relation_cache'
        tags:
            - { name: oro_entity.virtual_relation_provider, priority: -150 }

    oro_marketing_list.virtual_field_provider.marketing_list_item:
        class: Oro\Bundle\MarketingListBundle\Provider\MarketingListItemVirtualFieldProvider
        arguments:
            - "@oro_marketing_list.virtual_relation_provider.marketing_list"
        tags:
            - { name: oro_entity.virtual_field_provider, priority: -150 }

    oro_marketing_list.marketing_list.cache:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_marketing_list' }

    oro_marketing_list.provider.marketing_list_allowed_classes:
        class: Oro\Bundle\MarketingListBundle\Provider\MarketingListAllowedClassesProvider
        public: false
        arguments:
            - '@oro_marketing_list.marketing_list.cache'
            - '@oro_marketing_list.entity_provider.contact_information'

    oro_marketing_list.event_listener.user_before_value_render_listener:
        class: Oro\Bundle\MarketingListBundle\EventListener\ExtendFieldValueBeforeRenderListener
        arguments:
            - "@oro_entity_config.provider.entity"
            - phone: '@@OroMarketingList/MarketingList/ExtendField/phone.html.twig'
              email: '@@OroMarketingList/MarketingList/ExtendField/email.html.twig'
        tags:
            - { name: kernel.event_listener, event: oro.entity_extend_event.before_value_render, method: beforeValueRender }

    oro_marketing_list.event_listener.on_entity_change:
        class: Oro\Bundle\MarketingListBundle\EventListener\UpdateMarketingListOnEntityChange
        arguments:
            - '@oro_message_queue.message_producer'
            - '@logger'
            - '@oro_marketing_list.provider.marketing_list_allowed_classes'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: oro_featuretogle.feature, feature: marketing_list }

    oro_marketing_list.migration.demo_data_fixtures_listener.update_marketing_list:
        parent: oro_platform.event_listener.demo_data_fixtures_listener.abstract
        class: Oro\Bundle\MarketingListBundle\EventListener\UpdateMarketingListDemoDataFixturesListener
        arguments:
            - '@oro_marketing_list.entity_provider.contact_information'
            - '@event_dispatcher'
        calls:
            - [disableListener, ['oro_marketing_list.event_listener.on_entity_change']]
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.pre_load, method: onPreLoad }
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad }

    oro_marketing_list.workflow.condition.has_contact_information:
        class: 'Oro\Bundle\MarketingListBundle\Model\Condition\HasContactInformation'
        arguments:
            - "@oro_marketing_list.provider.contact_information_fields"
        tags:
            - { name: oro_action.condition, alias: has_contact_information }

    Oro\Bundle\MarketingListBundle\EntityConfig\EntityFieldConfiguration:
        tags:
            - oro_entity_config.validation.entity_config
