search:
    Oro\Bundle\CampaignBundle\Entity\Campaign:
        alias: oro_campaign
        label: oro.campaign.entity_plural_label
        route:
            name: oro_campaign_view
            parameters:
                id: id
        search_template: '@OroCampaign/Campaign/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Oro\Bundle\CampaignBundle\Entity\EmailCampaign:
        alias: oro_email_campaign
        label: oro.email_campaign.entity_plural_label
        route:
            name: oro_email_campaign_view
            parameters:
                id: id
        search_template: '@OroCampaign/EmailCampaign/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
            -
                name:                   campaign
                relation_type:          many-to-one
                relation_fields:
                    -
                        name: name
                        target_type: text
                        target_fields: [name]
            -
                name:                   marketingList
                relation_type:          many-to-one
                relation_fields:
                    -
                        name: name
                        target_type: text
                        target_fields: [name]
