acls:
    oro_marketing_list_delete:
        type: entity
        class: Oro\Bundle\MarketingListBundle\Entity\MarketingList
        permission: DELETE
        group_name: ""
        bindings: ~

    oro_marketing_list_removed_item_create:
        type: entity
        class: Oro\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem
        permission: CREATE
        group_name: ""
        bindings: ~

    oro_marketing_list_removed_item_delete:
        type: entity
        class: Oro\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem
        permission: DELETE
        group_name: ""
        bindings: ~

    oro_marketinglist_unsubscribed_item_create:
        type: entity
        class: Oro\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem
        permission: CREATE
        group_name: ""
        bindings: ~

    oro_marketinglist_unsubscribed_item_delete:
        type: entity
        class: Oro\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem
        permission: DELETE
        group_name: ""
        bindings: ~
