oro_marketing_list_bundle:
    resource:     "@OroMarketingListBundle/Controller"
    type:         annotation
    prefix:       /


#
# OLD REST API ROUTES
#

oro_api_contact_marketinglist_information_field_type:
    path: '/api/rest/{version}/marketinglist/contact-information/field/type.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListController::contactInformationFieldTypeAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_entity_marketinglist_contact_information_fields:
    path: '/api/rest/{version}/marketinglist/contact-information/entity/fields.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListController::entityContactInformationFieldsAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_delete_marketinglist:
    path: '/api/rest/{version}/marketinglists/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_remove_marketinglist_removeditem:
    path: '/api/rest/{version}/marketinglist/{marketingList}/remove/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListRemovedItemController::removeAction'
        _format: json
        version: latest
    requirements:
        marketingList: \d+
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_unremove_marketinglist_removeditem:
    path: '/api/rest/{version}/marketinglist/{marketingList}/unremove/{id}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListRemovedItemController::unremoveAction'
        _format: json
        version: latest
    requirements:
        marketingList: \d+
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_post_marketinglist_removeditem:
    path: '/api/rest/{version}/marketinglists/removeditems.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListRemovedItemController::postAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_delete_marketinglist_removeditem:
    path: '/api/rest/{version}/marketinglists/{id}/removeditem.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListRemovedItemController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_unsubscribe_marketinglist_unsubscribeditem:
    path: '/api/rest/{version}/marketinglist/{marketingList}/unsubscribe/{id}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListUnsubscribedItemController::unsubscribeAction'
        _format: json
        version: latest
    requirements:
        marketingList: \d+
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_subscribe_marketinglist_unsubscribeditem:
    path: '/api/rest/{version}/marketinglist/{marketingList}/subscribe/{id}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListUnsubscribedItemController::subscribeAction'
        _format: json
        version: latest
    requirements:
        marketingList: \d+
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_post_marketinglist_unsubscribeditem:
    path: '/api/rest/{version}/marketinglists/unsubscribeditems.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListUnsubscribedItemController::postAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_delete_marketinglist_unsubscribeditem:
    path: '/api/rest/{version}/marketinglists/{id}/unsubscribeditem.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListUnsubscribedItemController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_post_marketinglist_segment_run:
    path: '/api/rest/{version}/marketinglists/{id}/segments/runs.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\MarketingListBundle\Controller\Api\Rest\SegmentController::postRunAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1
