search:
    Oro\Bundle\MarketingListBundle\Entity\MarketingList:
        alias: oro_marketing_list
        label: oro.marketinglist.entity_plural_label
        route:
            name: oro_marketing_list_view
            parameters:
                id: id
        search_template: '@OroMarketingList/MarketingList/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
