security:

    firewalls:
        tracking_data:
            pattern:   ^/tracking/data/create
            provider:  chain_provider

oro_security:
    access_control:
        - { path: ^/tracking/data/create, roles: PUBLIC_ACCESS }
