system_configuration:
    groups:
        tracking:
            title:  oro.tracking.system_configuration.groups.tracking.title
            icon:  'fa-crosshairs'
        tracking_settings:
            title:  oro.tracking.system_configuration.groups.tracking_settings.title
            icon:  'fa-crosshairs'

    fields:
        oro_tracking.precalculated_statistic_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 60
            options:
                label: oro.tracking.system_configuration.fields.precalculated_statistic_enabled.label
                tooltip: oro.tracking.form.tooltip.precalculated_statistic_enabled
                required: false

        oro_tracking.dynamic_tracking_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 50
            options:
                label: oro.tracking.system_configuration.fields.dynamic_tracking_enabled.label
                tooltip: oro.tracking.form.tooltip.dynamic_tracking_enabled
                required: false

        oro_tracking.log_rotate_interval:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 40
            options:
                label: oro.tracking.system_configuration.fields.log_rotate_interval.label
                tooltip: oro.tracking.form.tooltip.log_rotate_interval
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.60: 60
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.30: 30
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.20: 20
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.15: 15
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.10: 10
                    oro.tracking.system_configuration.fields.log_rotate_interval.choices.5: 5

        oro_tracking.piwik_host:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            priority: 20
            options:
                label: oro.tracking.system_configuration.fields.piwik_host.label
                tooltip: oro.tracking.form.tooltip.piwik_host
                required: false

        oro_tracking.piwik_token_auth:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            priority: 10
            options:
                label: oro.tracking.system_configuration.fields.piwik_token_auth.label
                tooltip: oro.tracking.form.tooltip.piwik_token_auth
                required: false

        oro_tracking.wesite_configuration:
            ui_only: true
            type: Oro\Bundle\FormBundle\Form\Type\LinkType
            priority: 0
            options:
                label: false
                required: false
                resettable: false
                route: oro_tracking_website_index
                acl: oro_tracking_website_view
                title: oro.tracking.website_configuration

        oro_tracking.feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.tracking.feature_enabled

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            tracking:
                                priority: 50
                                children:
                                    tracking_settings:
                                        priority: 100
                                        children:
                                            - oro_tracking.dynamic_tracking_enabled
                                            - oro_tracking.precalculated_statistic_enabled
                                            - oro_tracking.log_rotate_interval
                                            - oro_tracking.piwik_host
                                            - oro_tracking.piwik_token_auth
                                            - oro_tracking.wesite_configuration
            marketing:
                children:
                    marketing_setup:
                        children:
                            marketing_settings:
                                children:
                                    marketing_features:
                                        children:
                                            - oro_tracking.feature_enabled

    api_tree:
        tracking:
            oro_tracking.dynamic_tracking_enabled: ~
            oro_tracking.log_rotate_interval: ~
            oro_tracking.piwik_host: ~
            oro_tracking.piwik_token_auth: ~
